(function() {var implementors = {};
implementors["petgraph"] = ["impl&lt;N,&nbsp;E,&nbsp;Item&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;Item&gt; for <a class='struct' href='petgraph/graphmap/struct.GraphMap.html' title='petgraph::graphmap::GraphMap'>GraphMap</a>&lt;N,&nbsp;E&gt; <span class='where'>where Item: <a class='trait' href='petgraph/trait.IntoWeightedEdge.html' title='petgraph::IntoWeightedEdge'>IntoWeightedEdge</a>&lt;E,&nbsp;NodeId=N&gt;, N: <a class='trait' href='petgraph/graphmap/trait.NodeTrait.html' title='petgraph::graphmap::NodeTrait'>NodeTrait</a></span>",];implementors["daggy"] = ["impl&lt;N,&nbsp;E,&nbsp;Item&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;Item&gt; for <a class='struct' href='daggy/petgraph/struct.GraphMap.html' title='daggy::petgraph::GraphMap'>GraphMap</a>&lt;N,&nbsp;E&gt; <span class='where'>where Item: <a class='trait' href='daggy/petgraph/trait.IntoWeightedEdge.html' title='daggy::petgraph::IntoWeightedEdge'>IntoWeightedEdge</a>&lt;E,&nbsp;NodeId=N&gt;, N: <a class='trait' href='daggy/petgraph/graphmap/trait.NodeTrait.html' title='daggy::petgraph::graphmap::NodeTrait'>NodeTrait</a></span>",];implementors["dsp"] = ["impl&lt;N,&nbsp;E,&nbsp;Item&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/iter/traits/trait.Extend.html' title='core::iter::traits::Extend'>Extend</a>&lt;Item&gt; for <a class='struct' href='petgraph/graphmap/struct.GraphMap.html' title='petgraph::graphmap::GraphMap'>GraphMap</a>&lt;N,&nbsp;E&gt; <span class='where'>where Item: <a class='trait' href='petgraph/trait.IntoWeightedEdge.html' title='petgraph::IntoWeightedEdge'>IntoWeightedEdge</a>&lt;E,&nbsp;NodeId=N&gt;, N: <a class='trait' href='petgraph/graphmap/trait.NodeTrait.html' title='petgraph::graphmap::NodeTrait'>NodeTrait</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
