(function() {var implementors = {};
implementors["sample"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i11/struct.I11.html' title='sample::types::i11::I11'>I11</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/u11/struct.U11.html' title='sample::types::u11::U11'>U11</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i24/struct.I24.html' title='sample::types::i24::I24'>I24</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i48/struct.I48.html' title='sample::types::i48::I48'>I48</a>",];implementors["dsp"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i11/struct.I11.html' title='sample::types::i11::I11'>I11</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/u11/struct.U11.html' title='sample::types::u11::U11'>U11</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i24/struct.I24.html' title='sample::types::i24::I24'>I24</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='sample/types/i48/struct.I48.html' title='sample::types::i48::I48'>I48</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
